language: generic
sudo: false

addons:
    apt:
        packages:
            - libgmp-dev

cache:
    directories:
        - $HOME/.stack


before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup

install:
    - stack build --coverage

script:
    - stack --no-terminal --skip-ghc-check test curl-client:test:curl-client-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test curl-client:test:curl-client-test --coverage
    - stack --no-terminal --skip-ghc-check test pacifica-metadata:test:pacifica-metadata-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test pacifica-metadata:test:pacifica-metadata-test --coverage
    - stack --no-terminal --skip-ghc-check test pacifica-metadata-servant:test:pacifica-metadata-servant-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test pacifica-metadata-servant:test:pacifica-metadata-servant-test --coverage
    - stack --no-terminal --skip-ghc-check test pacifica-metadata-servant-curl-client:test:pacifica-metadata-servant-curl-client-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test pacifica-metadata-servant-curl-client:test:pacifica-metadata-servant-curl-client-test --coverage
    - stack --no-terminal --skip-ghc-check test robinhood:test:robinhood-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test robinhood:test:robinhood-test --coverage
    - stack --no-terminal --skip-ghc-check test robinhood-extras:test:robinhood-extras-test --haddock --no-haddock-deps
    - stack --no-terminal --skip-ghc-check test robinhood-extras:test:robinhood-extras-test --coverage
